### ISSUE TITLE
Incompatible

### ISSUE THREAD

**Issue by MineTim** [JDevMC/BetterShutdownReloaded#1]
The plugin doesn't work under 1.12.! Is it possible to make it compatible for the 1.12.?

Greetings
Minecraft_Tim

**Comment by Coolfeather2** [comment]
Please update plugin

**Comment by JDevMC** [comment]
Hi,

I've finally updated the plugin. It now supports from 1.7.10 all the way up to 1.12.1. I'm sincerely sorry for this late update, but as I explained in the [discussion thread](https://www.spigotmc.org/threads/bettershutdown-reloaded.206931/page-2#post-2641478) of the plugin, I had nearly zero free time to dedicated to Gaming or Minecraft, let alone development. But, it's now updated, so, enjoy!

**Comment by JDevMC** [comment]
Hi,

I've finally updated the plugin. It now supports from 1.7.10 all the way up to 1.12.1. I'm sincerely sorry for this late update, but as I explained in the [discussion thread](https://www.spigotmc.org/threads/bettershutdown-reloaded.206931/page-2#post-2641478) of the plugin, I had nearly zero free time to dedicated to Gaming or Minecraft, let alone development. But, it's now updated, so, enjoy!
