### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MineTim** [JDevMC/BetterShutdownReloaded#2]
https://pastebin.com/w08vWgb7

Version 1.12

**Comment by MineTim** [comment]
Fixed

**Comment by JDevMC** [comment]
To clear things up, I accidentally uploaded a bad JAR file. To fix this, I removed the update(v1.0.3) and created it again, this time with a valid JAR file. I was in a hurry, so I couldn't explain it on the forum, and then I saw you(or someone else that reported this on Spigot) removed their message saying that it wasn't working, so I couldn't answer.

Thanks for reporting it.
